pipeline {
    agent any

    triggers {
        githubPush()
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Terraform') {
            steps {
                sh '''
                  if ! command -v terraform >/dev/null; then
                    curl -fsSL https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip -o terraform.zip
                    unzip terraform.zip
                    sudo mv terraform /usr/local/bin/
                  fi
                '''
            }
        }

        stage('Install Conftest') {
            steps {
                sh '''
                  curl -L https://github.com/open-policy-agent/conftest/releases/download/v0.56.0/conftest_0.56.0_Linux_x86_64.tar.gz | tar xz
                  sudo mv conftest /usr/local/bin/
                '''
            }
        }

        stage('Terraform Plan + Conftest') {
            steps {
                dir('02-conftest-terraform/terraform') {
                    sh '''
                      terraform init -input=false
                      terraform plan -out=tfplan -input=false
                      terraform show -json tfplan | conftest test --policy ../policies
                    '''
                }
            }
        }
    }
}

